### ISSUE TITLE
Gsheets plugin install fails on MacOS 10.11

### ISSUE THREAD

**Issue by jereze** [dataiku/dataiku-contrib#30]
```
Downloading/unpacking gspread>=0.2.5
  Downloading gspread-0.4.1.tar.gz
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/gspread/setup.py) egg_info for package gspread
    
Downloading/unpacking oauth2client>=1.5.0
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/oauth2client/setup.py) egg_info for package oauth2client
    
    warning: no previously-included files matching '*' found under directory 'tests'
Downloading/unpacking PyOpenSSL>=0.15.0
Downloading/unpacking awesome-slugify>=1.6.5
  Downloading awesome-slugify-1.6.5.tar.gz
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/awesome-slugify/setup.py) egg_info for package awesome-slugify
    
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.1 in /Applications/DataScienceStudio.app/Contents/Resources/kit/python.packages (from gspread>=0.2.5)
Downloading/unpacking httplib2>=0.9.1 (from oauth2client>=1.5.0)
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/httplib2/setup.py) egg_info for package httplib2
    
Downloading/unpacking pyasn1>=0.1.7 (from oauth2client>=1.5.0)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Downloading/unpacking pyasn1-modules>=0.0.5 (from oauth2client>=1.5.0)
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Downloading/unpacking rsa>=3.1.4 (from oauth2client>=1.5.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.6.1 in /Applications/DataScienceStudio.app/Contents/Resources/kit/python.packages (from oauth2client>=1.5.0)
Downloading/unpacking cryptography>=1.3.4 (from PyOpenSSL>=0.15.0)
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking regex (from awesome-slugify>=1.6.5)
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/regex/setup.py) egg_info for package regex
    
Downloading/unpacking Unidecode>=0.04.14,<0.05 (from awesome-slugify>=1.6.5)
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/Unidecode/setup.py) egg_info for package Unidecode
    
Downloading/unpacking idna>=2.0 (from cryptography>=1.3.4->PyOpenSSL>=0.15.0)
Downloading/unpacking setuptools>=11.3 (from cryptography>=1.3.4->PyOpenSSL>=0.15.0)
Downloading/unpacking enum34 (from cryptography>=1.3.4->PyOpenSSL>=0.15.0)
  Downloading enum34-1.1.6-py2-none-any.whl
Downloading/unpacking ipaddress (from cryptography>=1.3.4->PyOpenSSL>=0.15.0)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.3.4->PyOpenSSL>=0.15.0)
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/cffi/setup.py) egg_info for package cffi
    
Downloading/unpacking pycparser (from cffi>=1.4.1->cryptography>=1.3.4->PyOpenSSL>=0.15.0)
  Running setup.py (path:/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: gspread, oauth2client, PyOpenSSL, awesome-slugify, httplib2, pyasn1, pyasn1-modules, rsa, cryptography, regex, Unidecode, idna, setuptools, enum34, ipaddress, cffi, pycparser
  Running setup.py install for gspread
    
  Running setup.py install for oauth2client
    
    warning: no previously-included files matching '*' found under directory 'tests'
  Running setup.py install for awesome-slugify
    
  Running setup.py install for httplib2
    
  Running setup.py install for cryptography
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^
    1 error generated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/cryptography/setup.py", line 333, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs
        replace_conflicting=True
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match
        return self.obtain(req, installer)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain
        return installer(requirement)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'cc' failed with exit status 1
    Complete output from command /Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/bin/python -c "import setuptools, tokenize;__file__='/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/nn/dm60c6m50rv43gn37dgr0s5c0000gn/T/pip-CPbE5P-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/include/site/python2.7:
    c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found

#include <ffi.h>

         ^

1 error generated.

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/cryptography/setup.py", line 333, in <module>

    **keywords_with_side_effects(sys.argv)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs

    replace_conflicting=True

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match

    return self.obtain(req, installer)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain

    return installer(requirement)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg

    return cmd.easy_install(req)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1016, in run_setup

    raise DistutilsError("Setup script exited with %s" % (v.args[0],))

distutils.errors.DistutilsError: Setup script exited with error: command 'cc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/bin/python -c "import setuptools, tokenize;__file__='/Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/nn/dm60c6m50rv43gn37dgr0s5c0000gn/T/pip-CPbE5P-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/include/site/python2.7 failed with error code 1 in /Users/pierremenard/Library/DataScienceStudio/dss_home/pyenv/build/cryptography
Storing debug log for failure in /Users/pierremenard/.pip/pip.log
```

**Comment by jereze** [comment]
Running `xcode-select --install` in terminal to install the command line tools for xcode solved the issue.
