### ISSUE TITLE
Dataset audit plugin does not resolve variables

### ISSUE THREAD

**Issue by instanceofme** [dataiku/dataiku-contrib#52]
Notably `projectKey`, which is now by default in table names for relocation.

```
Executing master data query : SELECT COUNT(*) AS global_count, count(distinct "city") as "city_distinct",sum (case when "city" is null then 1  else 0 end) as "city_missing",count(distinct "year") as "year_distinct",sum (case when "year" is null then 1  else 0 end) as "year_missing",count(distinct "weekofyear") as "weekofyear_distinct",sum (case when "weekofyear" is null then 1  else 0 end) as "weekofyear_missing",count(distinct "total_cases") as "total_cases_distinct",sum (case when "total_cases" is null then 1  else 0 end) as "total_cases_missing" FROM "${projectKey}_submission_format_copy"
*************** Recipe code failed **************
Begin Python stack
Traceback (most recent call last):
  File "/home/dataiku/dataiku/data-dirs/dss-15800/jobs/SAS_V2/Build_sub_output_2017-10-06T08-46-53.714/compute_sub_output_NP/custompyrecipei0UzfWvE7IRG/python-exec-wrapper.py", line 3, in <module>
    execfile(sys.argv[1])
  File "/home/dataiku/dataiku/data-dirs/dss-15800/jobs/SAS_V2/Build_sub_output_2017-10-06T08-46-53.714/compute_sub_output_NP/custompyrecipei0UzfWvE7IRG/script.py", line 101, in <module>
    df = sqlexec.query_to_df(query)
  File "/home/dataiku/dataiku/installers/dataiku-dss-4.0.8/python/dataiku/core/sql.py", line 189, in query_to_df
    return _streamed_query_to_df(self._iconn, query, pre_queries, post_queries, self._find_connection_from_dataset, "sql", extra_conf)
  File "/home/dataiku/dataiku/installers/dataiku-dss-4.0.8/python/dataiku/core/sql.py", line 25, in _streamed_query_to_df
    data = data)
  File "/home/dataiku/dataiku/installers/dataiku-dss-4.0.8/python/dataiku/core/intercom.py", line 86, in backend_json_call
    return _handle_json_resp(backend_api_post_call(path, data, **kwargs), err_msg = err_msg)
  File "/home/dataiku/dataiku/installers/dataiku-dss-4.0.8/python/dataiku/core/intercom.py", line 152, in _handle_json_resp
    raise Exception("%s: %s" % (err_msg, _get_error_message(err_data).encode("utf8")))
Exception: None: During query 'SELECT COUNT(*) AS global_count, count(distinct "city") as "city_distinct",sum (case when "city" is null then 1  else 0 end) as "city_missing",count(distinct "year") as "year_distinct",sum (case when "year" is null then 1  else 0 end) as "year_missing",count(distinct "weekofyear") as "weekofyear_distinct",sum (case when "weekofyear" is null then 1  else 0 end) as "weekofyear_missing",count(distinct "total_cases") as "total_cases_distinct",sum (case when "total_cases" is null then 1  else 0 end) as "total_cases_missing" FROM "${projectKey}_submission_format_copy"' : ERROR: relation "${projectKey}_submission_format_copy" does not exist
  Position: 531
End Python stack
```

**Workaround:** use metrics

**Comment by louisza** [comment]
I use this piece of code to solve the issue:

project_key = dataset_config["projectKey"]
table = table.replace("${projectKey}",project_key)

**Comment by du-phan** [comment]
fixed
