### ISSUE TITLE
Google Sheet plugin : AttributeError: 'Worksheet' object has no attribute 'get_addr_int'

### ISSUE THREAD

**Issue by jereze** [dataiku/dataiku-contrib#91]
```
2018-11-14 09:51:13,290 INFO Connecting to parent at port 53541
2018-11-14 09:51:13,291 INFO Connected to parent at port 53541
2018-11-14 09:51:13,397 INFO Processing task: write_rows
2018-11-14 09:51:14,195 INFO Refreshing access_token
Traceback (most recent call last):
  File "/Applications/DataScienceStudio.app/Contents/Resources/kit/python/dataiku/connector/server.py", line 125, in serve
    write_rows(connector, schema, partitioning, partition_id, input)
  File "/Applications/DataScienceStudio.app/Contents/Resources/kit/python/dataiku/connector/server.py", line 63, in write_rows
    writer.close()
  File "/var/folders/k8/jbnml6rd43g6_3m16qrz1jxm0000gn/T/tmpgnqPYT/code.py", line 182, in close
    self.flush()
  File "/var/folders/k8/jbnml6rd43g6_3m16qrz1jxm0000gn/T/tmpgnqPYT/code.py", line 171, in flush
    cell_list = ws.range( 'A1:%s' % ws.get_addr_int(num_lines, num_columns) )
AttributeError: 'Worksheet' object has no attribute 'get_addr_int'
```

https://answers.dataiku.com/4271/exporting-a-dataset-to-google-sheets

**Comment by jereze** [comment]
Was very likely a problem of version of the libraries. Fixed in [1.0.0](https://github.com/dataiku/dataiku-contrib/pull/100) thanks to code env.
