### ISSUE TITLE
AttributeError when cell in text column only contains a number

### ISSUE THREAD

**Issue by silviutofan92** [dataiku/dataiku-contrib#98]
Some people who leave reviews might just say "5" (instead of "5 stars" or something), in which case the following appears:

[10:45:47] [INFO] [dku.utils]  - *************** Recipe code failed **************
[10:45:47] [INFO] [dku.utils]  - Begin Python stack
[10:45:47] [INFO] [dku.utils]  - Traceback (most recent call last):
[10:45:47] [INFO] [dku.utils]  -   File "/home/dataiku/dataiku-dss-5.0.2/python/dataiku/base/utils.py", line 51, in run_wrapped
[10:45:47] [INFO] [dku.utils]  -     runnable()
[10:45:47] [INFO] [dku.utils]  -   File "/home/dataiku/dataiku-dss-5.0.2/python/dataiku/base/utils.py", line 46, in _fn
[10:45:47] [INFO] [dku.utils]  -     exec_call(code)
[10:45:47] [INFO] [dku.utils]  -   File "/home/dataiku/dataiku-dss-5.0.2/python/dataiku/base/utils.py", line 42, in exec_call
[10:45:47] [INFO] [dku.utils]  -     exec(code() if callable(code) else code, copy(globals()))
[10:45:47] [INFO] [dku.utils]  -   File "<string>", line 79, in <module>
[10:45:47] [INFO] [dku.utils]  -   File "/home/dataiku/dss/plugins/installed/sentence-embedding/python-lib/sentence_embedding_utils.py", line 289, in preprocess_and_compute_sentence_embedding
[10:45:47] [INFO] [dku.utils]  -     clean_texts = map(clean_text, texts)
[10:45:47] [INFO] [dku.utils]  -   File "/home/dataiku/dss/plugins/installed/sentence-embedding/python-lib/sentence_embedding_utils.py", line 61, in clean_text
[10:45:47] [INFO] [dku.utils]  -     text = text.lower()  # lower text
[10:45:47] [INFO] [dku.utils]  - AttributeError: 'float' object has no attribute 'lower'

https://dsproj1.dataiku.com/projects/RECIPERECOMMENDER/jobs/Build_review_text_embeddings_2018-12-05T09-41-16.004/

**Comment by du-phan** [comment]
Will be fixed with #92
